### ISSUE TITLE
mysql connection 해제

### ISSUE THREAD

**Issue by Zimins** [NHNNEXT/2017-01-HUDI-MAC-CHAR#105]
클라이언트를 종료해도 connection 이 남아 있는 현상이 보임 
로그인 테스트를 많이하다가 Too many connections log 발견

**Comment by bbq923** [comment]
저도 발견했습니다...
Spring이 알아서 close()를 호출해 준다고 알고 있었는데 connection이 계속 남아있는 모양이네요.
급한 대로 mysql server에서 `service mysql restart` 명령어를 사용하면 connection을 날릴 수 있습니다.

**Comment by jbee37142** [comment]
`jdbcTemplate`을 사용하면 Spring이 알아서 `close()`를 호출하여 connection을 close를 하는게 아니라 내부적으로 connection pool을 사용해서 반납합니다 :) mysql을 재시동하는 것보다 서버를 재시동하는게 더 나을 것 같은데요?
