### ISSUE TITLE
Time calculator(Timer)

### ISSUE THREAD

**Issue by wkddngus5** [NHNNEXT/2017-01-HUDI-MAC-CHAR#115]
* 타이머를 사용해 낮, 밤, 투표 시간을 나누어 게임을 진행시킨다.
    * (투표가 종료된 시점에 서버측에서 이벤트를 발생시켜 소켓에 연결된 클라이언트들의 타이머를 동기화 한다?)

**Comment by Zimins** [comment]
@wkddngus5 방금 게임시작 테스트 하다가 본건데 , 타이머가 음수로 내려가는 버그가 있는듯 합니다.
(인원 5명, 한명 레디 껏다 켜다 하다 발견)

**Comment by wkddngus5** [comment]
형 근데 5명 테스트 어떻게 하셨어요? ㅎㅎ 크롬, 크롬 시크릿, 사파리, 파이어폭스... 4명까지 밖에 못하고 있어요

**Comment by Zimins** [comment]
크롬에서 탭띄우고 들어갔었어 아이디 다르게하고

**Comment by wkddngus5** [comment]
타이머 돌아가면 readyButton아예 안보이게 해놨습니다. :)

**Comment by Zimins** [comment]
5초 타이머일때는 버튼 보여야 하지 않아?

**Comment by wkddngus5** [comment]
타이머 가기 시작하면 취소 못하기로 했으니까 상관없을것 같아요

**Comment by Zimins** [comment]
아 취소 못하기로 했었군... 오키오키
