### ISSUE TITLE
Room이 가지고 있는 users 변수의 자료구조 변경 

### ISSUE THREAD

**Issue by bbq923** [NHNNEXT/2017-01-HUDI-MAC-CHAR#122]
현재 Room안에 있는 사용자들을
`private Set<User> users = Collections.synchronizedSet(new LinkedHashSet<>(CAPACITY));`
이렇게 보관하고 있습니다.

사용자가 Ready 버튼을 누르면 websocket으로 서버에 `{ userName }` 이 날아가도록 했는데, 이 userName으로 Room 안의 특정 user를 찾은 뒤 Status를 READY 또는 NOT_READY 로 바꿔주고, 그 변경사항을 ClientReady 라는 객체에 담아 Room 안의 사용자 들에게 broadcasting 해주고 싶습니다.

Map<nickname, User>을 쓰는 건 어떨까요? Set인 상태에서 특정 user를 찾을 수 있더라도 Set 자료구조를 유지할 메리트가 있을까요?

**Comment by jbee37142** [comment]
우선 관련된 이슈 #80 가 존재하는데, 이슈가 다시 등록되서 이전 이슈를 close합니다.

**Comment by jbee37142** [comment]
반대로 `Map` 자료구조를 사용하면 어떤 이점이 있나요? 그로 인해 발생하는 문제는 없나요?
> Talk is cheap. show me the code - Linus Torvalds

**Comment by bbq923** [comment]
우선 `Map` 으로 자료구조를 바꾸고, user가 room에 들어가는 이벤트를 websocket으로 room 안의 사용자들에게 뿌려주는 feature를 구현한 뒤 PR을 날리겠습니다. 코드를 보면서 같이 얘기해 보는 게 좋을 것 같아요
