### ISSUE TITLE
클라이언트에서 refresh 된 버그 상황

### ISSUE THREAD

**Issue by jbee37142** [NHNNEXT/2017-01-HUDI-MAC-CHAR#135]
클라이언트에서 refresh 된 버그 상황
* User 중복 체크

**Comment by bbq923** [comment]
클라이언트에서 User 중복 체크 (append 시 중복 확인)

**Comment by bbq923** [comment]
wkddngus5 님과 pair programming으로 해결해 보겠습니다~
