### ISSUE TITLE
게임 시작 시 역할을 할당하는 방법

### ISSUE THREAD

**Issue by bbq923** [NHNNEXT/2017-01-HUDI-MAC-CHAR#146]
PR: #145

**Comment by bbq923** [comment]
현재 4~8 명일 경우 각각에 대해 배정되는 직업의 종류는 4개로 일정하고 Mafia와 Citizen의 수만 변동되고 있는데,
인원 수가 다를 때 다르게 적용되어야 하는 룰이 어떤 게 있을까요?

**Comment by jbee37142** [comment]
일단 4명일 경우, 5명일 경우, 6명일 경우, ... 할당하는 직업의 종류가 다르기 때문에, 게임 진행 자체가 달라질 것 같습니다 :) 예를 들면 4명인 경우에는 의사라는 `Role`이 없을텐데, 의사가 있고 없고에 따라서 의사의 능력 발휘 시간에 한 명이 살아나느냐 그런 경우가 없느냐 등등...

**Comment by bbq923** [comment]
아 직업 종류의 수가 다른 경우도 있나 보네요. 코드에는 기본적으로 Docter, Police는 1명씩 깔고 가도록 되어 있어서 얘기해 보았습니다.
