### ISSUE TITLE
방 만들기

### ISSUE THREAD

**Issue by wkddngus5** [NHNNEXT/2017-01-HUDI-MAC-CHAR#20]
- Room Class로 static HashTable(동기화가 보장되는 HashMap)로 구현
- waiting_room에서 #make_room_form에 입력한 데이터로 방 만들기

**Comment by jbee37142** [comment]
`hashTable`보다 `ConcurrentHashMap` 사용하는게 더 좋을 것 같아요~

**Comment by wkddngus5** [comment]
"Hashtable은 스레드 안전성을 달성하기 위해 동기화 된 메서드를 사용하는 JDK 1.1 자체의 레거시 클래스입니다. Hashtable의 모든 메소드는 동기화되어 스레드의 수가 증가하면 충돌로 인해 상당히 느려집니다." 그러네요 ㅇㅇ

**Comment by jbee37142** [comment]
ConcurrentHashMap은 어떠한 이유로 HashTable에 비해 빠른지도 알아보면 도움이 될 것 같아요~
