### ISSUE TITLE
프로젝트 구조에 대해 다시 고려해 본다.

### ISSUE THREAD

**Issue by javajigi** [NHNNEXT/2017-01-HUDI-MAC-CHAR#21]
현재 안드로이드 프로젝트가 같은 저장소에 들어와 있다.
이와 같이 안드로이드 프로젝트가 같은 저장소를 사용한다면 현재 웹 프로젝트도 새로운 폴더를 만든 후 하위로 이동하는 것이 맞지 않을까?

**Comment by Zimins** [comment]
확실히 첫화면을 보면 약간의 혼동이 있을거 같다는 생각이 들기는 합니다.

**Comment by Zimins** [comment]
폴더 3개만 덩그러니 있으면 허전해 보일거 같기도 하고 ㅋㅋ

**Comment by JaeYeopHan** [comment]
readme 잘만들면허허저

**Comment by javajigi** [comment]
현재 프로젝트 구조는 가장 추천하지 않는 구조이다.
왜 그런지 논의해보면 좋겠다.

다음 둘 중 하나로 결정할 것을 추천한다.
각각의 장,단점이 있으니 같이 논의해 보고 결정하면 좋겠다.

* 선택 1 - MAC-CHAR 저장소 하나에 폴더를 기준으로 3개의 프로젝트가 위치
  * MAC-CHAR-WEB
  * MAC-CHAR-ANDROID
  * MAC-CHAR-IOS

* 선택 2 - 각 프로젝트마다 별도의 저장소 생성
  * MAC-CHAR-WEB
  * MAC-CHAR-ANDROID
  * MAC-CHAR-IOS

**Comment by jbee37142** [comment]
논의 결과 선택 1로 프로젝트 구조를 변경하기로 했습니다!
