### ISSUE TITLE
최종 데모에 포함했으면 하는 내용

### ISSUE THREAD

**Issue by jbee37142** [NHNNEXT/2017-01-HUDI-MAC-CHAR#213]
### 최종 데모에 포함했으면 하는 내용
이번 휴디프에서 자신이 중점을 두었고 잘했다고 생각하는 부분들을 자유롭게 댓글로 남겨주세요 :)
아래 예시 중에서 구체적인 내용이 들어가도 좋습니다.

#### 예시
* Github을 활용한 팀 프로젝트 같은 팀 프로젝트
* 프로젝트 중 진행되었던 코드리뷰
* 배우지 않았던 기술 스택을 도입하여 프로젝트를 진행
* 트렌드에 맞춰 기술 스택을 구성
* 짝 프로그래밍
* 통합 플랫폼 프로젝트(Web, Android, iOS)
* 슬럼프 극복 방법
* 회고를 통한 프로젝트 유지

수요일(5/31) 회의 (2시)전 까지 작성해주세요. 회의 때 내용을 결정하고 최종 데모 발표 준비를 논의합니다.

**Comment by bbq923** [comment]
프로젝트를 원격 서버에 배포하고 관리하는 역할을 맡았습니다. Ubuntu 14.04 서버에서 gradle 로 빌드되는 프로젝트를 배포하기 위해 필요한 패키지들을 리눅스 명령어와 npm을 사용해 다운 받고, 적절하게 환경 설정하는 작업을 했습니다. 또 다른 원격 서버에 mysql 데이터베이스를 설치해 연결한 것도 그 중 하나인데, 방화벽이나 사용자 권한, mysql의 포트 바인딩 등 문제가 될거라고 예상하지 못한 부분에서 많은 시간을 잡아 먹혔습니다. 그래도 막막하기만 했던 곳에서부터 시작해서 어찌 저찌 원격 서버에 정상적으로 배포할 수 있었습니다.

**Comment by Zimins** [comment]
안드로이드 클라이언트 부분을 개발했습니다. 
* 개경프때 배운 기초를 바탕으로 전보다 쉽게 개발.
* 배웠던 기능의 심화 기능을 익힘 (data update in recycler view)
* 이번 학기에는 클라이언트만 맡아서 집중이 가능했음.
* github 을 다른 사람과 써보면서 (fork 몇번을 초기화 했는지..)명령어들의 기능을 더욱 탄탄히 익힘 (stash, cherrypick, rebase ....)

**Comment by wkddngus5** [comment]
- 웹 서버&클라이언트 개발
- ECMAScript6 적용
- Gitub을 활용한 팀 프로젝트
- 짝 프로그래밍
- Socket을 이용한 서버, 클라이언트 통신
- test data만들기 

- 프로젝트 중반이 되면서 동력이 떨어지고 다소 느슨해지는 느낌이 있었는데 다행히 잘 극복하고 다시 개발할 수 있었던 것이 가장 의미있었음
- 게임이다보니 이제까지 개발했던 모든 프로그램 중 역대급으로 로직이 복잡했었고 그만큼 버그도 많아서 구현과 보수를 위한 고민을 많이 해 볼 수 있었음

**Comment by Yongjai** [comment]
#### iOS 클라이언트를 개발했고 아직도 하는 중인 Yongjai입니다 :)

* 먼저 수업 때 배웠던 것들을 직접 적용해 보고 응용해 볼 수 있어서 좋았습니다. 그러면서 막히거나 모르는 것들을 구글링하고 책을 찾아가면서 해결하는 즐거움을 느낄 수 있었고 그 만큼 좌절도 많이 해서 좋았습니다. 

* github이 팀 프로젝트에서 어떻게 사용될 수 있고 어떤 도움이 되는지 알 수 있었습니다. 

* 개인적으로 이번 프로젝트를 진행하면서 무엇이 부족하고 어떤 점을 보완해야 할 지 깨달을 수 있었던 점이 굉장히 의미 있는 것 같습니다. 앞으로 어떤 식으로 그리고 무엇을 공부하고 학습해야 하는지 알 수 있었습니다. 

* 여담으로 서버 띄우는게 굉장히 복잡하고 어려운 건줄 알았는데 아니라는 걸 알게 되어 흥미로웠습니다. 물론 그저 띄우는..ㅎㅎ

**Comment by jbee37142** [comment]
### 5/31 회의내용
* Issue 정리
* 마피아 돌려보기(x2)
* 최종 데모 시나리오 및 역할 분담

**Comment by jbee37142** [comment]
### 최종 발표 시나리오
* Intro
  * 맡았던 부분 소개 --> _재엽_

* 프로젝트 소개
  * 플랫폼 별 기술 스택 소개 --> _대훈/지민/용재_
  * 프로젝트 개요(마피아란 게임에 대한 간단한 소개) --> _대훈/우현_
 
* 프로젝트 진행 과정
  * Github 활용 (통합 Repository, Code Review) --> _재엽_
  * Pair programming --> _우현/대훈_
  * 슬럼프 극복기 --> _우현_
  * 백엔드와 클라이언트 사이의 커뮤니케이션 - 클라이언트만 개발했을 때의 장단점 --> _지민, 용재_

* 마피아 데모

발표자 : 한재엽(마피아)
발표자료 제작자 : 한재엽(마피아)

**Comment by jbee37142** [comment]
발표자료 초안입니다. 참고만 하세요. 편집은 제가 합니다 :)
[2017동계SW개발인턴_한재엽_redis_ops_bot.pdf](https://github.com/NHNNEXT/2017-01-HUDI-MAC-CHAR/files/1040433/2017.SW._._redis_ops_bot.pdf)
각자 정리 맡은 부분은 토요일(6/3) 18시까지 공유해주세요!

**Comment by javajigi** [comment]
마지막을 향해 달려가는 모습이 기대감을 높이네요.

데모 준비, 역할 분담, 기능 구현 과정이 지금까지의 어느 휴디 프로젝트보다 인상적으로 보여요. 
데모까지 몇 일 남지 않았는데 마무리가 좋을 것 같아요.

데모 중간에 마피아 게임을 한 게임 정도 같이 해볼 수 있는 시간을 넣어주면 더 좋을 것 같아요.

**Comment by jbee37142** [comment]
데모 때 진행할 예정입니다 :)

**Comment by javajigi** [comment]
@bbq923 
데모는 80 port로 하리라 기대한다. 
서버 port 변경되면 모바일도 변경해야 되니 미리 변경하고 공유할 것을 추천한다.

**Comment by javajigi** [comment]
@Yongjai 
> github이 팀 프로젝트에서 어떻게 사용될 수 있고 어떤 도움이 되는지 알 수 있었습니다.

지금 소스 코드를 보면 iOS 코드는 2개월 전에 최종 commit이 됐는데 어떻게 된거야? ㅋㅋ
남은 시간이 길지 않지만 이슈 관리 뿐만 아니라 소스 코드 관리에 대한 github의 효용성도 약간은 느껴보면 좋겠다.
