### ISSUE TITLE
프로젝트 폴더에 대한 이슈..

### ISSUE THREAD

**Issue by javajigi** [NHNNEXT/2017-01-HUDI-MAC-CHAR#24]
2017-01-HUDI-MAC-CHAR/MAC-CHAR-ANDROID/MafiaOnline

현재 위와 같은 구조로 되어 있는데 굳이 MAC-CHAR-ANDROID 아래에 MafiaOnline 구조로 갈 필요가 있나?
MafiaOnline 폴더를 제거하고 MAC-CHAR-ANDROID 아래에 소스 코드를 두면 안되는 이유가 있나?

내가 모르는 이유가 있으면 공유해 주면 좋겠고, 굳이 특별한 이유가 없다면 depth를 하나 더 들어갈 이유는 없을 것 같아서 의견 남긴다.

**Comment by jbee37142** [comment]
#23 PR에 @wlals822 에게 메세지를 남겼고 카톡방에도 공유했습니다! 제가 잘 몰라서 혹시 문제가 없으면 1 depth 줄이라고 했습니다.

**Comment by Zimins** [comment]
depth 하나 줄여서 PR 하겠습니다~

**Comment by jbee37142** [comment]
프로젝트 폴더 정리 완료했습니다.
