### ISSUE TITLE
4주차 월요일 수업 준비한다.

### ISSUE THREAD

**Issue by javajigi** [NHNNEXT/2017-01-HUDI-MAC-CHAR#28]
4주차(다음 주) 월요일 수업 진행을 다음과 같이 하려고 합니다.
수업 준비에 착오 없기 바래요.

* 현재까지 작업한 내용에 대한 데모. 프로토타입 수준이라도 괜찮음.
  * 웹, 안드로이드, iOS 파트별 진행
* PR 과정, Commit Log, 이슈 관리에 대한 피드백
  * PR 및 코드 리뷰 방법 공유 - 김태훈 교수
  * 현재 프로젝트 진행 과정에 대해 검토하고 피드백한다.
* 회고
  * 3주 동안의 과정에 대한 회고

**Comment by jbee37142** [comment]
@bbq923 @wlals822 @Yongjai @wkddngus5 
데모가 어디까지 진행될 수 있을까요?

**Comment by Zimins** [comment]
채팅이 UI  내에서 동작하게 해볼 수 있습니다. 로그인은 api 난이도를 봐야 시간이 측정될 듯 합니다.

**Comment by bbq923** [comment]
기본적인 회원가입, 로그인, 그 후 대기실에서 방을 클릭해 게임 방으로 입장하는 것, 게임 방 내에서 채팅하기 정도가 될 것 같습니다. 채팅 시 `[로그인한 사용자명] : [채팅 내용]` 의 형태로 나왔으면 좋겠는데, 내일 @JaeYeopHan 님과 그 부분에 대해 얘기를 좀 해보면 좋을 것 같습니다.

**Comment by Yongjai** [comment]
로그인 기능은 test까지 해봤는데 잘 작동하는 것으로 확인했습니다. 
그리고 오늘 chat 구현해서 test 해봤는데 실패...했습니다. Stomp 사용했다고 해서 Stomp가 어떤 식으로 작동하는 건지 보고 다시 한 번 구현해서 내일 안에 완성이 되면 월요일에는 로그인과 채팅을 같이 데모 할 수 있을 것 같습니다.

**Comment by jbee37142** [comment]
회고할 내용도 준비해주면 좋을 것 같네요 :) 생각나는대로 막 말하기 보다는...(ㅋㅋ)
* code review. 이대로 정말 괜찮은가?
* issue 등록하기. 왜 필요한지 모르겠고 귀찮은가?
* Git과 관련된 issue 이젠 좀 익숙해졌나?
etc...
