### ISSUE TITLE
Proejct Directory Name Fix

### ISSUE THREAD

**Issue by bbq923** [NHNNEXT/2017-01-HUDI-MAC-CHAR#31]
원격에서 디렉터리 들어갈 때마다 MAC-CHAR- 까지 이름이 겹쳐서 불편합니다.
WEB-MAC-CHAR, ANDROID-MAC-CHAR 로 이름을 변경하는 것이 좋을 것 같습니다.

**Comment by jbee37142** [comment]
바로 진행됬으면 좋겠어요! 너무 불편해요! 👍

**Comment by bbq923** [comment]
WEB은 다음번 PR할 때 프로젝트 명을 바꾸겠습니다. ANDROID는 터미널에서 단순히 디렉터리 명만 바꿀 경우
뭔가 문제가 생길 것 같은데... 어떤가요?

**Comment by jbee37142** [comment]
이건 현재 Github에 올라와 있는 안드로이드랑 웹만 이야기해서 하나의 PR로 올려서 바로 merge 해도 될 것 같아요~
안드로이드가 폴더 1 depth 줄이는 pr 할 때 같이하면 되겠네요!

**Comment by jbee37142** [comment]
merged
