### ISSUE TITLE
Room에서 User(?) or Player(?)를 어떻게 저장할 것인가

### ISSUE THREAD

**Issue by jbee37142** [NHNNEXT/2017-01-HUDI-MAC-CHAR#34]
Room에서 User(?) or Player(?)를 어떻게 저장할 것인가

**Comment by jbee37142** [comment]
Room의 id 를 어떻게 지정해줄 것인가

**Comment by javajigi** [comment]
사용자는 하나의 방에만 들어갈 수 있나요?
만약 그렇다면 Room에 입장하는 순간 User의 상태를 변경해서 관리할 필요도 있겠네요.

**Comment by bbq923** [comment]
### User vs Player
* Player 클래스를 따로 둘 필요가 있을까요? 방에 입장한 User의 상태를 변경하는 식으로 구분해도 충분하지 않을까요.
### Room의 id를 어떻게 지정해줄 것인가
* 사용자가 Room id로 방을 찾아서 입장하는 기능을 제공하고 있지 않으니, 십진수 숫자가 아니라 java.util.UUID 의 randomUUID() 메서드를 사용하는 것은 어떨까요?

**Comment by bbq923** [comment]
8명까지의 User를 담을 수 있는 Array와 0부터 7까지의 인덱스를 저장하는 Set을 두고, User가 들어올 때 
Array[Min(Set)] 에 저장하고 Set에서는 Min(Set) 값을 제외하고, 나갈 때는 Array의 User를 삭제하면서 Set에 해당 인덱스 값을 다시 추가하는 방법은 어떨까요?

**Comment by jbee37142** [comment]
@bbq923 죄송한데, 무슨 말인지 모르겠어요 :(

**Comment by bbq923** [comment]
제가 생각할때 Room에서 User를 표시하는 자연스러운 모습은 다음과 같습니다.

|0|1|2|3|
|---|---|---|---|                
|4|5|6|7|                         

* 방에 들어온 User들은 0번 부터 7번 자리까지 차례대로 위치시킨다. 
* User가 나가면 다른 User들의 위치는 바뀌지 않고, 해당 자리만 비운다.
* 새로운 User가 들어오면 비어있는 자리 중 앞자리 부터 차례대로 위치시킨다.

이런 식으로 보여주기 위해 User는 순서를 가지고 사이사이에 빈 자리가 있을 수 있는 Array 자료구조에 저장하고,
비어 있는 자리들을 관리하기 위해 index 값을 따로 Set으로 관리하는 방법을 생각해 보았습니다.
