### ISSUE TITLE
Primitive Type vs Wrapper Object

### ISSUE THREAD

**Issue by jbee37142** [NHNNEXT/2017-01-HUDI-MAC-CHAR#38]
`Primitive Type` vs `Wrapper Object`

**Comment by bbq923** [comment]
User에서는 primitive type long을 사용했습니다. Wrapper 객체로 사용한다면 어떤 이점이 있을까요? 
어느쪽이든 통일시키고 가는 게 좋을 것 같습니다.

**Comment by jbee37142** [comment]
http://mishadoff.com/blog/effective-java/ 이 사이트의 Item5 를 참고해보세요~
