### ISSUE TITLE
Apply Webpack 중 발생한 문제입니다.

### ISSUE THREAD

**Issue by jbee37142** [NHNNEXT/2017-01-HUDI-MAC-CHAR#39]
https://gist.github.com/JaeYeopHan/f8fef0af82a4db5b47c6344022535228

**Comment by randomfog42** [comment]
websocket 모듈의 `package.json`을 로드 하려다 파싱 에러 난 듯.
이거 로드 할 필요 없는 파일인데.. 어딘선가 websocket 모듈 사용하는데서 모듈 패스를 잘못 잡았는지 확인 바람

**Comment by jbee37142** [comment]
`websocket` 모듈은 `stompjs`모듈에서만 사용하고 있습니다... 아... 잘 안되네요:(

**Comment by jbee37142** [comment]
결국 라이브러리를 교체해서 해결했습니다! :)
