### ISSUE TITLE
application.properties에 있는 DB 정보 제외

### ISSUE THREAD

**Issue by jbee37142** [NHNNEXT/2017-01-HUDI-MAC-CHAR#43]
@javajigi
application.properties에 있는 DB 정보를 제외할 방법이 어떤 방법이 있을까요?

**Comment by javajigi** [comment]
Application.properties 파일을 git ignore 처리하면 된다. 서버는 수동으로 배포

**Comment by jbee37142** [comment]
예상했던게 맞았네요! 감사합니다! :)
