### ISSUE TITLE
DOM manipulation시 const 사용?

### ISSUE THREAD

**Issue by jbee37142** [NHNNEXT/2017-01-HUDI-MAC-CHAR#48]
@kishu 
javascript 코드에서 DOM manipulation 할 때, 한 번 select한 DOM이 변경되는 경우가 없는 경우에 const 사용해도 될 것 같은데, 여기서 궁금한 점이 select한 DOM의 `style` propetry를 조작하는 경우에는 사용할 수 없는 건가요?
```
const bar = document.querySelector('.classname');
bar.style = 'display';
```
babel 홈페이지에서는 해당 코드가 제대로 변환되기는 합니다.

**Comment by randomfog42** [comment]
const는 일기 전용 참조를 만드는 것임. 이것은 const가 참조하는 값이 불변을 말하는 것이 아님. 따라서 위 사용은 문제 없긴한데.. 익숙해 보이진 않음 ㅎㅎ

**Comment by jbee37142** [comment]
아.. 혼동했네요! :) 감사합니다!

**Comment by randomfog42** [comment]
써도 괜찮을 듯.... ㅎㅎ
