### ISSUE TITLE
원격 MySQL 서버 연결 문제 

### ISSUE THREAD

**Issue by bbq923** [NHNNEXT/2017-01-HUDI-MAC-CHAR#51]
원격 MySQL 서버에 연결하는 코드를 추가하니 서버 시작이 안 됩니다.
일단 로컬 MySQL 서버에 연결하는 코드로 변경해도 같은 에러로 시작이 안됩니다.
https://gist.github.com/bbq923/2dbf5435f60049ffdf135a1f323fa396

**Comment by jbee37142** [comment]
gist에 올려주신 코드를 좀 봤는데요, `build.gradle` 중 `dependencies` 에 아래 dependency 추가하고 해보세요!
```
compile "org.springframework.boot:spring-boot-starter-jdbc"
```

**Comment by bbq923** [comment]
추가하니 올라가네요! 감사합니다.
