### ISSUE TITLE
일정 산출

### ISSUE THREAD

**Issue by jbee37142** [NHNNEXT/2017-01-HUDI-MAC-CHAR#56]
프로젝트에 투입할 수 있는 개개인의 시간을 서로 나눠본 후, Sprint 1의 일정 산출에 참고한다.

**Comment by Zimins** [comment]
# _10시간 이상 쓰는거 예상입니다._

**Comment by bbq923** [comment]
저번 주 **Basic Login & Signup**에 들어간 시간 `20시간`
시간을 많이 잡아 먹었던 부분
* DB 연동
* 서버 설정, gradle 빌드

**Comment by wkddngus5** [comment]
* 자구알 전날인 월, 수 빼고 나머지 평일 3시간 정도.
* 주말엔 5시간
3x3+5 = 14시간

**Comment by jbee37142** [comment]
* Code review는 PR update한 뒤 30분 안에 바로 시작.
* 평일 : 월(2) / 화(2) / 수(3) / 목(3) / 금(x)
* 주말 : 5 + 5
total : 10 + (10)시간

**Comment by Yongjai** [comment]
* 월 :: HUDI & iOS_Basic // (1h)
* 화 :: 자구알 // (3h)
* 수 :: HUDI & iOS_Basic // (불가능)
* 목 :: 자구알 & 모컴개 // (2h)
* 금 :: 공강 // (5h 이상)
* 토 :: 5h 이상
* 일 :: 5h 이상

   Total : 20h 정도
