### ISSUE TITLE
방 나가기 기능

### ISSUE THREAD

**Issue by jbee37142** [NHNNEXT/2017-01-HUDI-MAC-CHAR#78]
방 나가기 기능 추가하기
* 브라우저의 뒤로 가기 기능을 막거나 뒤로 가기 기능을 사용해도 나갈 수 있도록
* 게임을 시작하면 뒤로 가기 기능을 막아도 될 듯

**Comment by wkddngus5** [comment]
- 현재 방에 자신밖에 없으면 방 폭파
